In [4]:
from Environment import ConnectFour3DEnv

In [2]:
game = ConnectFour3DEnv()
game.apply_action([3, 3])
game.apply_action([3, 3])
game.apply_action([3, 3])

game.apply_action([2, 2])
game.apply_action([2, 2])

game.apply_action([1, 1])

print(game.check_win())

game.switch_player()

game.apply_action([0, 0])
game.apply_action([1, 1])
game.apply_action([2, 2])
game.apply_action([3, 3])

print(game.check_win())
print(game.grid)

False
True
[[[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  1]]

 [[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  1  0]
  [ 0  0  0 -1]]

 [[ 0  0  0  0]
  [ 0  1  0  0]
  [ 0  0 -1  0]
  [ 0  0  0 -1]]

 [[ 1  0  0  0]
  [ 0 -1  0  0]
  [ 0  0 -1  0]
  [ 0  0  0 -1]]]


In [ ]:
game = ConnectFour3DEnv()
game.apply_action([3, 3])
game.apply_action([3, 3])
game.apply_action([3, 3])
game.apply_action([3, 3])



print(game.check_win())
print(game.grid)

True
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 1]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 1]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 1]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 1]]]


In [15]:
game = ConnectFour3DEnv()
game.reset()

print(len(game.grid))

game.step((0, 0))

print(len(game.grid))

game.step((1, 3))
game.step((1, 3))
game.step((1, 3))
game.step((0, 0))
game.step((1, 3))
game.step((1, 0))
game.step((1, 3))
game.step((1, 3))




# print(game.grid)

4
After switching to player 2:
[[[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]

 [[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]

 [[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]

 [[-1  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]]
4
After switching to player 1:
[[[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]

 [[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]

 [[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]

 [[ 1  0  0  0]
  [ 0  0  0 -1]
  [ 0  0  0  0]
  [ 0  0  0  0]]]
After switching to player 2:
[[[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]

 [[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]

 [[ 0  0  0  0]
  [ 0  0  0 -1]
  [ 0  0  0  0]
  [ 0  0  0  0]]

 [[-1  0  0  0]
  [ 0  0  0  1]
  [ 0  0  0  0]
  [ 0  0  0  0]]]
After switching to player 1:
[[[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]

 [[ 0  0  0  0]
  [ 0 

(array([[[ 0,  0,  0,  0],
         [ 0,  0,  0,  1],
         [ 0,  0,  0,  0],
         [ 0,  0,  0,  0]],
 
        [[ 0,  0,  0,  0],
         [ 0,  0,  0,  1],
         [ 0,  0,  0,  0],
         [ 0,  0,  0,  0]],
 
        [[-1,  0,  0,  0],
         [ 0,  0,  0, -1],
         [ 0,  0,  0,  0],
         [ 0,  0,  0,  0]],
 
        [[-1,  0,  0,  0],
         [-1,  0,  0,  1],
         [ 0,  0,  0,  0],
         [ 0,  0,  0,  0]]]),
 -1,
 True)

In [1]:
import torch
print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("CUDA version:", torch.version.cuda)
    print("GPU name:", torch.cuda.get_device_name(0))


PyTorch version: 2.5.1+cu118
CUDA available: True
CUDA version: 11.8
GPU name: NVIDIA GeForce RTX 2060
